# Generated by Django 4.2.13 on 2024-05-13 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=18)),
                ('gender', models.CharField(choices=[('m', 'man'), ('w', 'woman')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StoreIcecream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=6, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Ice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('пломбир', 'Пломбир'), ('лед', 'Лед'), ('эскимо', 'Эскимо')], max_length=25)),
                ('price', models.IntegerField(default=0)),
                ('all_ice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeicecream')),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('m', 'man'), ('w', 'woman')], max_length=1)),
                ('father', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father', to='store.people')),
                ('monther', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother', to='store.people')),
            ],
        ),
    ]
